### PR TITLE
BIg refactoring of states

### PR DESCRIPTION
**Pull request by GermanBluefox**
- channels may not have channels inside
- roles were wrong
- small code refactoring
- add device search

### CODE REVIEW

**Comment by foxriver76** [comment]
Do we still want to support nodejs4? Elsewise I will remove it from the tests.
Also I'm a big fan of minimalistic configuration on user side and would not implement configurations like poll and request intervals (also it seems to work well), but you are the boss.  ;)

**Comment by GermanBluefox** [comment]
We leave node4 support.

**Comment by GermanBluefox** [comment]
For "minimalistic" juts create a "Advanced tab" and move settings there. 
Can you do that. Or I can implmenent it.

**Comment by GermanBluefox** [comment]
Ich habe implemented

**Comment by foxriver76** [comment]
I will have a closer look at it when I'm back home, will merge it into an experimental branch for now. Thanks for the great work. 

One question: Why is having a channel in another channel prohibited?

**Comment by GermanBluefox** [comment]
Because all known logic is built about:
- device => channel => state
- channel => state



ср, 25 июл. 2018 г., 15:12 Max Hauser <notifications@github.com>:

**Pull request merged**
