### PR TITLE
(bluefox) try to use state.xml

### PR DESCRIPTION
**Pull request by GermanBluefox**
I can read by my 1300 denon following xml page.

Can you see something by your device?
https://github.com/GermanBluefox/ioBroker.denon/blob/master/test/lib/example.xml

http://' + IP + '/goform/formNetAudio_StatusXml.xml?ZoneName=MAIN+ZONE

You can get at once all important values of device (volume, title, random, repeat, input, surround, mute, subwoofer, sleep)

Can you look at that?

### CODE REVIEW

**Comment by foxriver76** [comment]
In my case it will work (X1200W). The newer AVR's which support HEOS aren't accessable via http. I will test and merge it, it looks like a good solution for the problem. I already forgot about the http-requests. Thank you again. :1st_place_medal:

**Comment by cernst1980** [comment]
I have a X4400H and HTTP URL is not working.

I only get:
Error 403: Forbidden
Access Forbidden

**Comment by foxriver76** [comment]
Yes, as far as I know: AVR's newer than X4300 don't support HTTP --> https://forum.iobroker.net/viewtopic.php?f=36&t=14628&start=100#p159115

Does your AVR support HEOS @cernst1980 ?

**Comment by foxriver76** [comment]
So it will only work for the older models.

**Comment by cernst1980** [comment]
Yes, it has HEOS, but I have not tried to use the protocol so far.

**Comment by foxriver76** [comment]
@GermanBluefox  I checked your code. What you do is to check for the "Now Playing" value. It's the same as checking the display content if it contains the now playing. 

I have a better solution for this case. We dont need the XMLs. If displayContent0 contains 'now playing' we know that isPlaying should be true. When the display content changes the AVR automatically sends the NSE messages, so we dont need an extra superFastPolling variable.

**Comment by foxriver76** [comment]
I added both for the avrs which support it. so the States will only be shown for those who can use them.

**Pull request closed without merging**
